#include "edge_drm.h"

#include <openssl/sha.h>

#include <chrono>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <random>
#include <sstream>
#include <iomanip>
#include <stdexcept>

namespace HoundTTS {

// Windows epoch offset: seconds between 1601-01-01 and 1970-01-01
static constexpr int64_t WIN_EPOCH = 11644473600LL;
// 100-nanosecond intervals per second (Windows FILETIME units)
static constexpr int64_t TICKS_PER_SEC = 10000000LL;
// Round-down interval: 5 minutes in 100-ns ticks
static constexpr int64_t ROUND_TICKS = 300LL * TICKS_PER_SEC;

std::atomic<double> EdgeDRM::clockSkewSeconds_{0.0};

void EdgeDRM::AdjustClockSkew(double seconds) {
    // Atomic add via CAS loop
    double old_val = clockSkewSeconds_.load(std::memory_order_relaxed);
    while (!clockSkewSeconds_.compare_exchange_weak(
        old_val, old_val + seconds,
        std::memory_order_relaxed, std::memory_order_relaxed)) {
    }
}

double EdgeDRM::GetCorrectedTimestamp() {
    auto now = std::chrono::system_clock::now();
    double unixSec = std::chrono::duration<double>(now.time_since_epoch()).count();
    return unixSec + clockSkewSeconds_.load(std::memory_order_relaxed);
}

std::string EdgeDRM::GenerateSecMsGec() {
    double unixSec = GetCorrectedTimestamp();

    // Convert to Windows file time (100-ns ticks since 1601-01-01)
    int64_t ticks = static_cast<int64_t>((unixSec + WIN_EPOCH) * TICKS_PER_SEC);

    // Round down to nearest 5 minutes
    ticks -= ticks % ROUND_TICKS;

    // Build string to hash: "<ticks><trusted_client_token>"
    std::string strToHash = std::to_string(ticks) + EDGE_TRUSTED_CLIENT_TOKEN;

    // SHA256
    unsigned char hash[SHA256_DIGEST_LENGTH];
    SHA256(reinterpret_cast<const unsigned char*>(strToHash.c_str()),
           strToHash.size(), hash);

    // Convert to uppercase hex
    char hex[SHA256_DIGEST_LENGTH * 2 + 1];
    for (int i = 0; i < SHA256_DIGEST_LENGTH; ++i) {
        std::sprintf(hex + i * 2, "%02X", hash[i]);
    }
    return std::string(hex, SHA256_DIGEST_LENGTH * 2);
}

std::string EdgeDRM::SecMsGecVersion() {
    return std::string("1-") + EDGE_CHROMIUM_FULL_VERSION;
}

std::string EdgeDRM::GenerateMuid() {
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_int_distribution<int> dist(0, 15);

    char hex[33];
    const char* hexChars = "0123456789ABCDEF";
    for (int i = 0; i < 32; ++i) {
        hex[i] = hexChars[dist(gen)];
    }
    hex[32] = '\0';
    return std::string(hex);
}

// connectionId must be a 32-char uppercase hex string (no dashes, URL-safe).
// Generated by GenerateMuid()/GenerateConnectionId().
std::string EdgeDRM::BuildWebSocketUrl(const std::string& connectionId) {
    // Validate format: exactly 32 uppercase hex chars — URL-safe, no encoding needed.
    if (connectionId.size() != 32) {
        throw std::invalid_argument(
            "EdgeDRM::BuildWebSocketUrl: connectionId must be 32 chars, got " +
            std::to_string(connectionId.size()) + " (\"" + connectionId + "\")");
    }
    for (char c : connectionId) {
        if (!((c >= '0' && c <= '9') || (c >= 'A' && c <= 'F'))) {
            throw std::invalid_argument(
                "EdgeDRM::BuildWebSocketUrl: connectionId contains invalid char '" +
                std::string(1, c) + "' (expected uppercase hex A-F, 0-9) in \"" +
                connectionId + "\"");
        }
    }
    std::string url = "wss://speech.platform.bing.com/consumer/speech/synthesize/"
                      "readaloud/edge/v1?TrustedClientToken=";
    url += EDGE_TRUSTED_CLIENT_TOKEN;
    url += "&ConnectionId=";
    url += connectionId;
    url += "&Sec-MS-GEC=";
    url += GenerateSecMsGec();
    url += "&Sec-MS-GEC-Version=";
    url += SecMsGecVersion();
    return url;
}

std::string EdgeDRM::BuildUserAgent() {
    return std::string("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
           " (KHTML, like Gecko) Chrome/") + EDGE_CHROMIUM_MAJOR_VERSION +
           ".0.0.0 Safari/537.36 Edg/" + EDGE_CHROMIUM_MAJOR_VERSION + ".0.0.0";
}

std::string EdgeDRM::BuildOrigin() {
    return "chrome-extension://jdiccldimpdaibmpdkjnbmckianbfold";
}

std::string EdgeDRM::BuildCookieHeader() {
    return "muid=" + GenerateMuid() + ";";
}

} // namespace HoundTTS
